services:
  client:
    networks:
      - cards-network
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pleiades_client
    ports:
      - '1512:80'
networks:
  cards-network:
    external: true
